### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by mbennett-uoe** [mbennett-uoe/whiiif#6]
- [x] Minimal set without Solr
  - [x] Does Flask start
  - [x] ~~Do dirs referenced in config exist~~ - This is really an integration test (see #18)
  - [x] ~~Can test files be read / parsed~~ - Now part of first SOLR set test
- [x] Set with Solr
  - [x] ~~Index a document~~ - This is really an integration test (see #18)
  - [x] IIIF search endpoint
     - [x] Correct Solr query generated
     - [x] Response well formatted (context block)
     - [x] Correct `@id` generated
     - [x] Correct number of results returned - in the `total` value and also list lengths
     - [x] Single part correct `resources` block returned
     - [x] Single part correct `hits` block returned
     - [x] Multi-part response correct `resources` block returned
     - [x] Multi-part response correct `hits` block returned
     - [x] Scaling if `scale` in Solr response
     - [x] `ignored` parameter populated correctly
     - [x] "Graceful" failure if anything goes wrong with Solr query
  - [x] Collection search endpoint
     - [x] Correct Solr query generated
     - [x] Correct number of results returned
     - [x] Result `manifest_url` correct
     - [x] Result `total_results` correct
     - [x] Correct `canvas_id` returned
     - [x] Correct `region` returned
     - [x] Single highlight `coords` correct
     - [x] Multi-highlight `coords` blocks correct
     - [x] Snippet scaling correct (downsizing all results by fixed ratio)
     - [x] ~Scaling if `scale` in Solr response~ - Need to fix #12 first!!
     - [x] "Graceful" failure if anything goes wrong with Solr query
  - [x] Snippet search endpoint
     - [x] Correct Solr query generated
     - [x] Correct number of results returned
     - [x] Result `manifest_url` correct
     - [x] Result `total_results` correct
     - [x] Correct `canvas_id` returned
     - [x] Correct `region` returned
     - [x] Single highlight `coords` correct
     - [x] Multi-highlight `coords` blocks correct
     - [x] Scaling if `scale` in Solr response
     - [x] "Graceful" failure if anything goes wrong with Solr query
     - [x] `snips` parameter working correctly
